services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - 80:80
      # - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  backend:
    build: backend
    ports:
      - 8000:8000
    env_file:
      - backend/.env
  frontend:
    build: frontend
    ports:
      - 8090:80
    depends_on:
      - backend
