services:
  backend:
    build: backend
    ports:
      - 8000:8000
    env_file:
      - backend/.env
  frontend:
    build: frontend
    ports:
      - 80:80
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=ws://backend:8000